from django.urls import path
from . import views

urlpatterns = [
    # Auth
    path("",                        views.login_view,          name="login"),
    path("auth/login/",             views.credential_login,    name="credential_login"),
    path("auth/register/",          views.credential_register, name="credential_register"),
    path("auth/guest/",             views.guest_login,         name="guest_login"),
    path("auth/operator/",          views.operator_login,      name="operator_login"),
    path("auth/google/",            views.google_auth_start,   name="google_auth_start"),
    path("auth/google/callback/",   views.google_auth_callback,name="google_auth_callback"),
    path("auth/logout/",            views.logout_view,         name="logout"),
    path("auth/me/", views.auth_me, name="auth_me"),
    # Pages
    path("app/",                   views.demo,                name="demo"),
    path("app/dashboard/",         views.demo_dashboard,      name="demo_dashboard"),
    path("app/anomaly/",           views.demo_anomaly,        name="demo_anomaly"),
    path("app/security/",          views.demo_security,       name="demo_security"),
    path("app/critic/",            views.demo_critic,         name="demo_critic"),
    path("app/x402/",              views.demo_x402,           name="demo_x402"),
    path("app/updates/",           views.demo_updates,        name="demo_updates"),
    path("app/analytics/",         views.demo_analytics,      name="demo_analytics"),
    path("app/swarm/",             views.demo_swarm,          name="demo_swarm"),
    path("app/kavacha/",           views.demo_kavacha,        name="demo_kavacha"),
    path("app/wallet/",            views.demo_wallet,         name="demo_wallet"),
    path("app/trading/",           views.demo_trading,        name="demo_trading"),
    path("app/eraya-casper.pdf",   views.demo_ppt_pdf,        name="demo_ppt_pdf"),
    path("dashboard/",              views.legacy_redirect, name="dashboard"),
    path("map/",                    views.legacy_redirect, name="map"),
    path("a2a-chat/",               views.legacy_redirect, name="a2a_chat"),
    path("self-healing/",           views.legacy_redirect, name="self_healing"),
    path("agents/",                 views.legacy_redirect, name="agents_default"),
    path("agents/<str:agent_type>/",views.legacy_redirect, name="agents"),
    path("domains/",                views.legacy_redirect, name="domains_default"),
    path("domains/<str:domain>/",   views.legacy_redirect, name="domains"),
    path("incidents/",              views.legacy_redirect, name="incidents"),
    path("audit-log/",              views.legacy_redirect, name="audit_log"),
    path("context-graph/",          views.legacy_redirect, name="context_graph"),
    path("security/",               views.legacy_redirect, name="security"),
    path("settings/",               views.legacy_redirect, name="settings"),
    # API
    path("api/fire-drill/",         views.fire_drill,          name="fire_drill"),
    path("api/simulations/",        views.simulation_history,  name="simulation_history"),
]
