# Generated by Django 5.2.14 on 2026-07-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantEngineState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.IntegerField(default=3)),
                ('autopilot', models.BooleanField(default=False)),
                ('start_cash_usd', models.FloatField(default=10000.0)),
                ('cash_usd', models.FloatField(default=10000.0)),
                ('pos_units', models.FloatField(default=0.0)),
                ('avg_entry', models.FloatField(default=0.0)),
                ('peak_equity', models.FloatField(default=10000.0)),
                ('day', models.DateField(blank=True, null=True)),
                ('day_start_equity', models.FloatField(default=10000.0)),
                ('day_trades', models.IntegerField(default=0)),
                ('last_trade_at', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quant engine state',
            },
        ),
        migrations.CreateModel(
            name='QuantTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.FloatField(db_index=True)),
                ('side', models.CharField(max_length=4)),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('notional_usd', models.FloatField()),
                ('fee_usd', models.FloatField(default=0.0)),
                ('pnl_usd', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.JSONField(default=dict)),
                ('guardian', models.JSONField(default=dict)),
                ('risk', models.IntegerField(default=3)),
                ('settle_status', models.CharField(default='unsigned', max_length=16)),
                ('settle_tx', models.CharField(blank=True, default='', max_length=128)),
                ('explorer_url', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
