# Generated by Django 5.2.14 on 2026-07-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('direction', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], max_length=8)),
                ('service', models.CharField(max_length=96)),
                ('counterparty', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('negotiated', 'Negotiated'), ('locked', 'Locked'), ('delivered', 'Delivered'), ('cleared', 'Cleared'), ('disputed', 'Disputed')], default='negotiated', max_length=16)),
                ('verdict', models.CharField(blank=True, default='', max_length=32)),
                ('usdc', models.FloatField(default=0.0)),
                ('pts_delta', models.IntegerField(default=0)),
                ('audit_id', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
